POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "chaitanya123",
  "password": "jhondoe@123"
}
###
GET http://localhost:3001/admin/

### 
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "chaitanya",
  "password": "jhondoe@123"
}
###
POST http://localhost:3001/projects
Content-Type: application/json

{
    "title":"Jobby App",
    "description":"Implemented Jobby application which is a basic model of job searching platform ",
    "projectUrl":"https://chaijobsapp.ccbp.tech/"
}
###
GET http://localhost:3001/projects
